[versions]
compileSdk = "35"
minSdk = "24"
targetSdk = "35"
agp = "8.9.0"
kotlin = "2.0.21"
activityCompose = "1.10.1"
composeBom = "2025.01.00"
okHttp = "4.12.0"
navigationCompose = "2.8.8"
koin = '3.4.0'
retrofit = '2.9.0'
junitJupiter = "5.11.3"
mockk = "1.13.5"
coroutines = "1.7.3"
junitUI = "1.2.1"
espresso = "3.6.1"
uiTestJunit4Android = "1.7.8"
uiTestManifest = "1.7.8"
uiTestRunner = "1.6.2"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
koin = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okHttp" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }

# Unit Tests
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }
junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
ui-test-junit4 = { group = "androidx.test.ext", name = "junit", version.ref = "junitUI" }
ui-test-koin = { group = "io.insert-koin", name = "koin-test", version.ref = "koin" }
ui-test-koin-junit4 = { group = "io.insert-koin", name = "koin-test-junit4", version.ref = "koin" }
ui-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
ui-test-espresso-intents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "espresso" }
ui-test-espresso-contrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "espresso" }
ui-test-mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okHttp" }
ui-test-junit4-android = { group = "androidx.compose.ui", name = "ui-test-junit4-android", version.ref = "uiTestJunit4Android" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "uiTestManifest" }
ui-test-runner = { module = "androidx.test:runner", version.ref = "uiTestRunner" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
